#!/bin/sh
KEXTDIR=/Library/Extensions
chmod -R go-w $KEXTDIR/SatSmartDriver.kext 
chown -R root:wheel $KEXTDIR/SatSmartDriver.kext 
chmod -R go-w $KEXTDIR/SatSmartLib.plugin
chown -R root:wheel $KEXTDIR/SatSmartLib.plugin
kextutil $KEXTDIR/SatSmartDriver.kext
exit 0
